### ISSUE TITLE
Server crash when connecting steam powered drill to steam tank with steam pipe

### ISSUE THREAD

**Issue by PlacidK** [cyanobacterium/SteamAdvantage#10]
Crash log -> http://pastebin.com/6y1CNuAM

I had to remove the block with MCedit before i could restart the server

**Comment by DrPlantabyte** [comment]
I'll see if I can find the problem. I'm guessing something changed in Forge and my mod is too out of date.

**Comment by DrPlantabyte** [comment]
Fixed in version 2.0.3. Electric advantage had the same bug and it is now fixed there too.
