### ISSUE TITLE
steam hammer

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/SteamAdvantage#2]
The steam hammer in 1.3.1 when using an automated method to reload it will fill up one slot and then overflow to the other slots. No errors in either consoles.

**Comment by DrPlantabyte** [comment]
Oops. That's a byproduct of an effort to simplify and generalize the item handler implementation.

**Comment by DrPlantabyte** [comment]
Fixed in version 1.3.3. This bug was also present in the blast furnace.
