### ISSUE TITLE
enableBetterVillagers...

### ISSUE THREAD

**Issue by Schrubbls** [cyanobacterium/SteamAdvantage#6]
Hi there,
I want to use all the advantages but i keep getting this errorlog 

http://pastebin.com/aAAnzRjL

Is this a bug? or am I failing hard?

PS: i dont know where to post it

**Comment by DrPlantabyte** [comment]
Update Base Metals to version 1.7.2 or downgrade Power Advantage and its add-ons to earlier versions (second to latest version).
