### ISSUE TITLE
modid 

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/SteamAdvantage#7]
This is still not a critical error, but I thought I pointed this out either last year, or the year before that.

When I load your mod into MULTIMC it says it's name is "Example Mod". None of your other mods do this.

**Comment by DrPlantabyte** [comment]
Oops, that's embarrassing. I am prone to forgetting bug reports if I don't haev the opportunity to fis them immediately.

**Comment by squirrelkiller** [comment]
I just popped in to report this... it made it kinda annoying to credit you for a modpack I am working on. So consider it an encouragement to get on it. LOL.

**Comment by DrPlantabyte** [comment]
Will be fixed in next release.
