### ISSUE TITLE
Crash on 1.9 Forge 1863

### ISSUE THREAD

**Issue by TrikSteve** [cyanobacterium/SteamAdvantage#8]
Pastebin below

http://pastebin.com/raw/MR3SFzbW

**Comment by DrPlantabyte** [comment]
Thanks for the info. I'll update when I can get to it. I'm using Forge build 1859 at the moment.

**Comment by DrPlantabyte** [comment]
I updated to Forge build 1865 and still not having any problems. Either this was a problem with one particular version of Forge or a problem with the InventoryTweaks mod.

**Comment by TrikSteve** [comment]
Ok. Will give it a try Sunday night.
